### ISSUE TITLE
Cookielaw banner has white bars either side

### ISSUE THREAD

**Issue by rsmith013** [cedadev/apptheme-mezzanine-ceda-div#10]
![Screenshot 2019-11-13 at 16 24 40](https://user-images.githubusercontent.com/22395703/68782983-26f5dd00-0632-11ea-866e-3c9af2a393d9.png)

**Comment by mjpritchard** [comment]
Fixed in https://github.com/cedadev/fwtheme-django/commit/5d9f466c0ce287be4cafe846fa832973e0120ae2#diff-39ddc969e2e15fe212d5234dace130e7
